### ISSUE TITLE
Bot can't connect

### ISSUE THREAD

**Issue by graphiks** [dborodin836/TF2-GPTChatBot#65]
Whenever i open the executable, i get a `Couldn't connect! Retrying in 4 second...`
I have properly added the launch options with nothing else, and put my gpt3 key. Using chatgpt from the gui works fine. Am i doing something wrong?

**Comment by dborodin836** [comment]
Hi @graphiks.

Thanks for reporting this issue. 

_I apologize for the delay in responding to your issue._

If the problem is still persisting, you can try changing the port in the config file to `42465`. Please ensure that you have configured everything correctly and that the logfile path is accurate.

To make this change, locate the line in the config file that says `RCON_PORT=27015`, and modify it to `RCON_PORT=42465`. Additionally, update your launch options: 
`-rpt -usercon +ip 0.0.0.0 +rcon_password password +hostport 42465 +con_timestamp 1 +net_start`.

Additionally, an updated version of the application will be released soon, which might address this issue.

Let me know if you need further assistance.

**Comment by graphiks** [comment]
no problem; wouldve been a epic gamer move if u waited 10 years
