### ISSUE TITLE
[TEXT-GENERATION-PUBLIC-API] might be deprecated

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#84]
--public-api is unreliable, and it doesn't work for me and a couple of other users.
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/ca9fda85-9bd2-407e-8bc4-a2abd5e9f539)
https://github.com/oobabooga/text-generation-webui/issues/3570
I have a feeling the code that handles the API calls is outdated since text-gen's API was updated _fairly recently._
It'd be super cool if you could update it or just get rid of it altogether.
Updating it would let people fine-tune the model's parameters and customize the instructions to fit their model's needs while also keeping things private.

**Comment by teufortressIndustries** [comment]
The way I use it now is just a workaround ([Third-party application setup](https://github.com/oobabooga/text-generation-webui/blob/main/docs/12%20-%20OpenAI%20API.md#Third-party-application-setup)), and I have no idea what parameters it uses, the AI most of the time talks some kind of nonsense and doesn’t follow instructions that well.

**Comment by dborodin836** [comment]
Hi @teufortressIndustries.

Thanks for bringing up this issue.

Yeah, it seems that the code might be outdated, as it was implemented around 7 months ago and hasn't been actively maintained since then neither i used that feature. While I would love to update or remove the code, I currently don't have the necessary spare time to work on it. However, I will do my best to take a look at it next week or so and see what can be done to address this issue.
